[package]
name = "rooky-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
pgn-reader.workspace = true
shakmaty.workspace = true
web-sys.workspace = true
nostr-minions.workspace = true
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"

