[package]
name = "external"
version = "0.1.0"
edition = "2021"

[dependencies]
rooky-core.workspace = true
futures-util.workspace = true
wasm-bindgen-futures.workspace = true
wasm-streams.workspace = true
web-sys.workspace = true
wasm-bindgen-test.workspace = true
futures-core = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
